---
title: "Sesiones"
site: distill::distill_website
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

1. [Introducción a R](./slides/intro_r.html)

2. [Manejo de datos en R, parte 1](./slides/manejo_datos_r_1.html)

3. [Manejo de datos en R, parte 2](./slides/manejo_datos_r_2.html)

4. [Revisión del modelo lineal con muestras finitas](./slides/recordatorio_mco.html)

5. [Teoría asintótica para MCO](./slides/teoria_asintotica.html)

6. [Estimadores extremos](./slides/estimadores_extremos_mv.html)

7. [Modelos de variable dependiente categórica](./slides/dependiente_categorica.html)

8. [Inferencia estadística](./slides/inferencia_estadistica.html)

9. [Modelos con variable dependiente de conteo](./slides/conteo.html)

10. [Modelos de riesgo y sobrevivencia](./slides/duracion.html)

11. [Modelos de selección](./slides/muestra_seleccionada.html)

12. [Variables instrumentales](./slides/variables_instrumentales.html)

14. [Temas de errores estándar](./slides/errores_estandar.html)

15. [Modelos y estimadores de panel lineal](./slides/panel_lineal.html)

18. [Métodos no paramétricos y semi paramétricos](./slides/no_parametricos.html)

18. [Regresión cuantil](./slides/cuantil.html)

19. Econometría espacial

20. Introducción a la inferencia causal

21. Métodos experimentales

22. Diferencia en diferencias

23. Propensity score matching

24. Diseños con discontinuidades

25. Control sintético